customuser/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('home.urls'))
]

home/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from .views import answer, setting

app_name = 'home'

urlpatterns = [
    path('', answer, name='home'),
    path('answer', answer, name='answer'),
    path('setting',  setting, name='setting'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .views import UserView, signup, reset

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='users:login'), name='logout'),
    path('profile/',  login_required(UserView.as_view()), name='profile'),
    path('signup/', signup, name='signup'),
    path('reset/', reset, name='reset')
]

home/models.py
from django.db import models

# Create your models here.

class FineTunedModels(models.Model):
    model_id = models.CharField(max_length=50)
    user_email = models.CharField(max_length=50)

users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class UserManager(BaseUserManager):

  def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
    if not email:
        raise ValueError('Users must have an email address')
    now = timezone.now()
    email = self.normalize_email(email)
    user = self.model(
        email=email,
        is_staff=is_staff, 
        is_active=True,
        is_superuser=is_superuser, 
        last_login=now,
        date_joined=now, 
        **extra_fields
    )
    user.set_password(password)
    user.save(using=self._db)
    return user

  def create_user(self, email, password, **extra_fields):
    return self._create_user(email, password, False, False, **extra_fields)

  def create_superuser(self, email, password, **extra_fields):
    user=self._create_user(email, password, True, True, **extra_fields)
    return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=254, unique=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    last_login = models.DateTimeField(null=True, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)

home/forms.py
from .models import models
from django import forms

class ModelsForm(forms.ModelForm):
    
    class Meta:
        model = Task
        fields - "__all__"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
 
class SignUpForm(UserCreationForm):
    password2 = None
    class Meta:
        model = User
        fields = ('email','name',)

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# from django.contrib.auth import login, authenticate
from django.views.generic.detail import DetailView
from .scrap_ft import main, completion
from .models import FineTunedModels
# import openai
# openai.api_key = "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"
# from .forms import SignUpForm

@login_required

class HomeView(DetailView):
    template_name = 'answer.html'

    def get_object(self):
        print(self.request.user)
        
        return self.request.user

@login_required
def answer(request):
    if request.method == 'POST':
        # form = SignUpForm(request.POST)
        form = request.POST
        question = form.get("question", "")
        model_id=""
        try:
            usr = FineTunedModels.objects.get(user_email=request.user)
            model_id = usr.model_id
        except FineTunedModels.DoesNotExist:
            pass
        answer = completion(model_id.strip(" "), question)
        print("=============", question)
        # answer = "this is response"
        
        context = {'question':question, 'answer':answer}
        return render(request, 'answer.html', context)
    return render(request, 'answer.html')

@login_required
def setting(request):
    if request.method == 'POST':
        form = request.POST
        doc_url = form.get("doc_url", "")
        print('====================',doc_url)
        model_id=main(doc_url, str(request.user))
        # model_id='adfasdfasdfasdfdf980'
        print('====================',model_id)
        
        print('========================', model_id)
        try:
            FineTunedModels.objects.get(user_email=request.user)
            FineTunedModels.objects.filter(user_email=request.user).update(model_id=model_id)
        except FineTunedModels.DoesNotExist:
            usr = FineTunedModels(user_email=request.user, model_id=model_id) # create new model instance
            usr.save()
        
        context = {'code':200, 'doc_url':doc_url, 'model_id':model_id}
        return render(request, 'setting.html', context)
    return render(request, 'setting.html')

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.views.generic.detail import DetailView

from .forms import SignUpForm


class UserView(DetailView):
    template_name = 'profile.html'

    def get_object(self):
        print(self.request.user)
        return self.request.user


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        # print(form)
        if form.is_valid():
            user = form.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(request, email=user.email, password=raw_password)
            print(user)
            if user is not None:
                login(request, user)
            else:
                print("user is not authenticated")
            return redirect('home:answer')
    form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def reset(request):
    if request.method == 'POST':
        # form = SignUpForm(request.POST)
        # # print(form)
        # if form.is_valid():
        #     user = form.save()
        #     raw_password = form.cleaned_data.get('password1')
        #     user = authenticate(request, email=user.email, password=raw_password)
        #     if user is not None:
        #         login(request, user)
        #     else:
        #         print("user is not authenticated")
        return redirect('users:profile')
    else:
        form = SignUpForm()
    return render(request, 'reset.html')

home/templates/answer.html
{% extends "layout.html" %}
{% block content %}
    <div class="container my-bg">
        <div class="row">
            <div class="col col-md-3 content-center">
                <legend class="mb-4 mt-5 subtitle">SmartResponse</legend>
                <div>
                    <fieldset class="form-group sidbar-subtitle">
                        Question
                    </fieldset>
                    <legend class="mb-4 sidebar-description">Copy/past the tech question your prospect has and SmartResponse will generate you the most relevant answer basd on documentation you specified in "Settings"</legend>
                </div>
                <div class="sidebar-action">
                    <a class="btn bg-purple mt-4 pl-4 pr-4 full" href="{% url 'home:answer' %}" >Get Answer</a>
                    <a class="btn mt-4 pl-4 pr-4 full" href="{% url 'home:setting' %}" >Setting</a>
                </div>
            </div>
            <div class="col col-8">
                <div class="home-content">
                    <form id="answer-form" method="POST" action="{% url 'home:answer' %}">
                        {% csrf_token %}
                        <label for = "question">Smart response</label>
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" id="question" name="question" value="{{ question }}">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="submit" id="sendbtn"  onclick="Loading()" ><i class="fas fa-location-arrow"></i></button>
                            </div>
                        </div>
                    </form>
                    <div class = "form-group mt-10">
                        <label for = "name">Smart response</label>
                        <textarea class = "form-control" id="answer" name="answer" rows = "8">{{answer}}</textarea>
                    </div>
                    <div class="form-group">
                        <button class="btn bg-yellow mt-4 pl-4 pr-4 item-right" onclick="CopyText()" id="copybtn">Copy</button>
                    </div>
                </div>
            </div>
            <div class="col col-md-1">
                <div class="helpful-part content-center">
                    <legend class="mb-4">How helpful was it</legend>
                    <legend class="mb-4">Helpful</legend>
                    <legend class="mb-4">Not helpful</legend>
                </div>
            </div>
        </div>
    </div> 

{% endblock content %}

{% block scripts %}
    <script>
        function CopyText() {
            var text = document.getElementById('answer')
            text.select();
            document.execCommand('copy')
        }
    </script>
    <script>
        function Loading() {
            var btn = document.getElementById('sndbtn')
            btn.disabled= true
            var form = document.getElementById('answer-form')
            form.submit()
        }
    </script>
    <script>
        let answer = document.getElementById('answer');
        let btn = document.getElementById('copybtn');
        if(!answer.value)
            btn.disabled=true
        let senbtn = document.getElementById('sendbtn');
        let question = document.getElementById('question');
        if(!question.value)
            senbtn.disabled=true
        question.addEventListener('change', ()=>{
            if(!question.value)
                senbtn.disabled=true
            else
                senbtn.disabled=false
        });
    </script>
{% endblock scripts %}

home/templates/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="{% static 'jquery.blockUI.js' %}"></script>
    <script src="https://malsup.github.io/jquery.blockUI.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    {% if title %}
        <title>SmartResponse - {{title}}</title>
    {% else %}
        <title>SmartResponse</title>
    {% endif %}

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand font-weight-bold" href="{% url 'home:home' %}"><i class="fas fa-file"></i> SmartResponse</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:answer' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user }}</a>
            <a href="{% url 'users:logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            
            {% else %}
            <a href="{% url 'users:login' %}" class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>
            
            <a href="{% url 'users:signup' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
            {% endif %}
            
        </div>
    </nav>
    
    {% block content %}
      
    {% endblock  %}
    {% block scripts %}
      
    {% endblock  %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    {% comment %} <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script> {% endcomment %}
    <script src="{% static 'main.js' %}"></script>
  </body>
</html>

home/templates/setting.html
{% extends "layout.html" %}
{% block content %}   
    <div class="container my-bg">
      <div class="row">
        <div class="col col-md-3 col-sm-6 content-center">
            <legend class="mb-4 mt-5 subtitle">SmartResponse</legend>
            <div>
                <fieldset class="form-group sidbar-subtitle">
                    Question
                </fieldset>
                <legend class="mb-4 sidebar-description">

                    <p>*simply put the main documentation page link your company has and we will take case of the rest.
                    </p>
                    e.g. 
                    <p>
                        https://www.twillo.com/docs
                    </p>
                    <p>
                        https://stripe.com/docs
                    </p>
                </legend>
            </div>
            <div class="sidebar-action">
                <a class="btn mt-4 pl-4 pr-4 full" href="{% url 'home:answer' %}" >Get Answer</a>
                <a class="btn bg-purple mt-4 pl-4 pr-4 full" href="{% url 'home:setting' %}" >Setting</a>
            </div>
        </div>
        <div class="col col-9">
            <div class="home-content-setting">
                {% if model_id %}
                <div class="alert alert-success">
                    {{ model_id }}
                </div>
                {% endif %}
                <form id="setting-form" method="POST" action="{% url 'home:setting' %}">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <div class="form-group">
                            <label class="content-label" for="password">Documentation URL</label>
                            <input type="text" class="form-control" id="doc_url" name="doc_url" required value={{ doc_url }} >
                            <div class="valid-feedback">Valid.</div>
                            <div class="invalid-feedback">Please fill out this field.</div>
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <button class="btn bg-yellow mt-4 pl-4 pr-4 item-right" id="updatebtn" type="submit" onclick="Loading()" >Update</button>
                    </div>
                </form>
            </div>
        </div>
      </div>
        
    </div> 

{% endblock content %}

{% block scripts %}
    <script>
        function Loading() {
            var btn = document.getElementById('updatebtn')
            btn.disabled= true
            var form = document.getElementById('setting-form')
            form.submit()
            
        }
    </script>
    <script>
        $(document).ready(function() { 
            $('#updatebtn').click(function() { 
                $.blockUI({ css: { 
                    border: 'none', 
                    padding: '15px', 
                    backgroundColor: '#000', 
                    '-webkit-border-radius': '10px', 
                    '-moz-border-radius': '10px', 
                    opacity: .5, 
                    color: '#fff' 
                } }); 
            }); 
        }); 
        
    </script>
{% endblock scripts %}

users/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'main.css' %}">
    {% if title %}
        <title>SmartResponse - {{title}}</title>
    {% else %}
        <title>SmartResponse</title>
    {% endif %}

</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand font-weight-bold" href="{% url 'home:home' %}"><i class="fas fa-file"></i> SmartResponse</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home:answer' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        
            {% if user.is_authenticated %}
            <a href="{% url 'users:profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user }}</a>
            <a href="{% url 'users:logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            
            {% else %}
            <a href="{% url 'users:login' %}" class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>
            
            <a href="{% url 'users:signup' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
            {% endif %}
            
        </div>
    </nav>
    
    <div class="container my-bg">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% block content %}
      
    {% endblock  %}
</div> 
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'main.js' %}"></script>
  </body>
</html>

users/templates/login.html
{% extends "base.html" %}
{% block content %}
<div>
    <legend class="mb-4 mt-5 title">SmartResponse</legend>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4 subtitle">Log In</legend>
                <legend class="mb-4 description">Get started with your account.</legend>
                <div class="form-group">
                    <label for="username">Email address</label>
                    <input type="text" class="form-control" id="username" placeholder="example@gmail.com" name="username" required>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" placeholder="****************" name="password" required>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                </div>
            </fieldset>
            <small class="text-muted">
                Forgot your password? <a class="ml-2" href="{% url 'users:reset' %}">Reset</a>
            </small>
            <div class="form-group">
                <button class="btn bg-purple mt-4 pl-4 pr-4" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'users:signup' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
</div>
{% endblock content %}

users/templates/profile.html
{% extends "base.html" %}
{% block content %}
<div>
    <legend class="mb-4 mt-5 title">SmartResponse</legend>
    <div class="content-section">
            <fieldset class="form-group">
                {{ object }}
            </fieldset>
    </div>
</div>
{% endblock content %}

users/templates/reset.html
{% extends "base.html" %}
{% block content %}
<div class="content-center">
    <legend class="mb-4 mt-5 title">SmartResponse</legend>
    <div class="content-section">
        <legend class="mb-4 description">Done! We've sent an email with a reset link. Click the link in the email to set a new passwork.</legend>
    </div>
    <a class="btn bg-purple mt-4 pl-4 pr-4" href="{% url 'users:login' %}">Go back to login page</a>
</div>
{% endblock content %}

users/templates/signup.html
{% extends "base.html" %}
{% block content %}
<div>
    <legend class="mb-4 mt-5 title">SmartResponse</legend>
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="mb-4">Create your free account</legend>
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="form-group">
                    <label for="name">Full Name</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                </div>
                <div class="form-group">
                    <label for="password">Create password</label>
                    <input type="password" class="form-control" id="password" name="password1" required>
                    <div class="valid-feedback">Valid.</div>
                    <div class="invalid-feedback">Please fill out this field.</div>
                </div>
            </fieldset>
            <input class="ml-2" type="checkbox" class="form-check-input" name="agreepolicy">
            <small class="text-muted ml-1">
                I agree and understand the Teams & Conditions
            </small>
            <div class="form-group">
                <button class="btn bg-purple mt-4 pl-4 pr-4" type="submit" id="signup">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an account? <a class="ml-2" href="{% url 'users:login' %}">Login</a>
            </small>
        </div>
    </div>
</div>
{% endblock content %}